package ao.apbot.drools.plugin.core

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

global org.apache.mina.core.session.IoSession session;

dialect  "mvel"

rule "help"

    when
        pkg : MsgPacket(command matches "help")
    then
    	session.write(pkg.getReply("Core commands: ECHO TIME "));
end

rule "Auth"

//      Chrisax Id[16728]
//      Workboy Id[603863]
//      Doodi Id[683837]

    when
        pkg : MsgPacket(pkg.getCharacterId()==16728 || pkg.getCharacterId()==603863 || pkg.getCharacterId()==683837)
    then
    	session.write(pkg.getReply("you are admin"));
end



rule "Echo"

    when
        pkg : MsgPacket(command matches "echo")
    then
  		session.write(pkg.getReply(pkg.getMsg()));
end

rule "test join"

    when
        pkg : MsgPacket(command matches "test-join")
    then
  		session.write(new PrivateMessagePacket(45212, "join"));
end

rule "test accept"

    when
        pkg : MsgPacket(command matches "test-accept")
    then
  		session.write(new PrivateChannelAcceptPacket(45212));
end


rule "test lvl"

    when
        pkg : MsgPacket(command matches "test-lvl")
    then
  		session.write(new PrivateMessagePacket(45212, "lvl 200"));
end


rule "box"

    when
        pkg : MsgPacket(command matches "test-whois")
    then
  		session.write(new PrivateMessagePacket(45212, "whois Bobsan"));
end