language: java

jdk:
  - oraclejdk8

env:
  global:
    - secure: "TY6GK3z1YSneyeuYownNGwbRDtletgYDc3NzmFDeapsgsCQpAE9nXJlZWxUmXDazcaZgTSXoelecV+HfLkG3CDECfsgOgG393EAU5Sl8n4rv4yFzaDTnQ5P1864yj/WJX3xQyezmZ+C9xL9AuDATbQXD3GDSx2AjtMwWXeMAyp74v7YmjfXaIuZf/lQ+8OAZeDoVGMWc+SRvXMfVDjDgPFAfWtbxPw86td6nwVJlT7Qt21rfYexHZjzQFJHDX5qtbr2TnNYxmau+Au5obLHDMpJ3E1hJZgk8CM2qRBBHBXT/uiBMjXRD4AWGOGyBhtNDheIH+2yF7SLSBAtawibRH51uznX16kYt4TOXCDDjQw5amtL1Yw6prFVfjUOjlwRZiZwbrGyCyqpKw2lp67E7R2plP4E5wD6R43wbc28HvW3VmdMcs+wFhMmSlMF1OK8P68rSyv54vTQFEdjM7hBS0QDqpFsHf9EygP9DA7dhDUNA0yfWnC1gm8TJfDSoInwEeeGE0g0ZLd9jeXjVJIRnt4/GcwiLaloWrwOakBI66Eh4ekC0GbCZS8UEziqHN7jrWmQMGI/i65I+IMEwMZeifrtZuF0jgWe1caahgbX6CNkXrcLqTV6t7b84pWa4y1tsAwULPOWEFahpDqj0cvApxqh7p+Z1xZqsS4RZ4/aL+uI="

  addons:
    coverity_scan:
      project:
        name: "senare/apbot"
        description: "Build submitted via Travis CI"
      notification_email: senare@gmail.com
      build_command_prepend: "mvn clean"
      build_command:   "mvn -DskipTests=true install"
      branch_pattern: master
