package ao.apbot.drools.core

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

global org.apache.mina.core.session.IoSession session;

dialect  "mvel"

rule "Help"

    when
        pkg : MsgPacket(command matches "help") && !( pkg : ChannelMessagePacket )
    then
    	session.write(pkg.getReply("Core commands: <font color=#FFFF00> echo time </font>"));
end

rule "Echo"

    when
        pkg : MsgPacket(command matches "echo") && !( pkg : ChannelMessagePacket )
    then
  		session.write(pkg.getReply(pkg.getMsg()));
end

rule "Time command"

    when
        pkg : MsgPacket(command matches "time") && !( pkg : ChannelMessagePacket )
    then
        session.write(pkg.getReply(Time.get()));
end