package ao.apbot.drools.core

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

global org.apache.mina.core.session.IoSession session;

dialect  "mvel"

rule "Help"

    when
        pkg : PrivateMessagePacket(command matches "help") || pkg : PrivateChannelMessagePacket(command matches "help") ||
    then
    	session.write(pkg.getReply("Core commands: <font color=#FFFF00> echo time </font>"));
end

rule "Echo"

    when
        pkg : PrivateMessagePacket(command matches "echo") || pkg : PrivateChannelMessagePacket(command matches "echo")
    then
  		session.write(pkg.getReply(pkg.getMsg()));
end

rule "Time command"

    when
        pkg : PrivateMessagePacket(command matches "time") || pkg : PrivateChannelMessagePacket(command matches "time") 
    then
        session.write(pkg.getReply(Time.get()));
end