package ao.apbot.drools.org

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

import ao.apbot.drools.core.*;

global org.apache.mina.core.session.IoSession session;

dialect  "mvel"

rule "Help"

    when
        pkg : PrivateMessagePacket(command matches "help") || pkg : PrivateChannelMessagePacket(command matches "help") 
    then
    	session.write(pkg.getReply("Org commands: <font color=#FFFF00> mish level titlelevel ailevel oe calc </font>"));
end

rule "Level"

    when
        pkg : PrivateMessagePacket(command matches "level") || pkg : PrivateChannelMessagePacket(command matches "level")
    then
  		session.write(pkg.getReply(Level.get(pkg.getParam(1))));
end

rule "Mish"

    when
        pkg : PrivateMessagePacket(command matches "mish") || pkg : PrivateChannelMessagePacket(command matches "mish")
    then
  		session.write(pkg.getReply(Level.mish(pkg.getParam(1))));
end

rule "AiLevel"

    when
        pkg : PrivateMessagePacket(command matches "ailevel") || pkg : PrivateChannelMessagePacket(command matches "ailevel")
    then
  		session.write(pkg.getReply(Level.get(pkg.getParam(1))));
end

rule "TitleLevel"

    when
        pkg : PrivateMessagePacket(command matches "titlelevel") || pkg : PrivateChannelMessagePacket(command matches "titlelevel")
    then
  		session.write(pkg.getReply(Level.get(pkg.getParam(1))));
end

rule "OverEquip"

    when
        pkg : PrivateMessagePacket(command matches "oe") || pkg : PrivateChannelMessagePacket(command matches "oe")
    then
  		session.write(pkg.getReply(OverEquip.get(pkg.getParam(1))));
end

rule "Calc"

    when
        pkg : PrivateMessagePacket(command matches "calc") || pkg : PrivateChannelMessagePacket(command matches "calc")
    then
        session.write(pkg.getReply(Calc.get(pkg.getParam(1))));
end
