package apbot

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

global org.apache.mina.core.session.IoSession session;
global ao.apbot.AoChatBot manager;

dialect  "mvel"

rule "Create bot"

    when
        pkg : MsgPacket(command matches "create")
    then
  		session.write(pkg.getReply(manager.newBot(pkg.getParam(2), pkg.getParam(3), pkg.getParam(4), pkg.getParam(1))));
end

rule "Activate bot"

    when
        pkg : MsgPacket(command matches "activate")
    then
  		session.write(pkg.getReply(manager.active(pkg.getParam(1), true)));
end

rule "Deactivate bot"

    when
        pkg : MsgPacket(command matches "deactivate")
    then
		session.write(pkg.getReply(manager.active(pkg.getParam(1), false)));
end

rule "Spawn bot"

    when
        pkg : MsgPacket(command matches "spawn")
    then
  		session.write(pkg.getReply(manager.spawn(pkg.getParam(1))));
end

rule "Kill bot"

    when
        pkg : MsgPacket(command matches "kill")
    then
  		session.write(pkg.getReply(manager.kill(pkg.getParam(1))));
end

