package apbot

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.*;

global org.apache.mina.core.session.IoSession session;
# global ao.apbot.AoChatBot manager;

dialect  "mvel"

rule "Create bot"

    when
        pkg : MsgPacket(command matches "create")
    then
    	# aochatbot.newBot(pkg.getParam(2), pkg.getParam(3), pkg.getParam(4), pkg.getParam(1));
  		session.write(pkg.getReply("Created bot "));
end

rule "Activate bot"

    when
        pkg : MsgPacket(command matches "activate")
    then
	 	# aochatbot.active(pkg.getParam(1), true);
  		session.write(pkg.getReply("Activate bot " + pkg.getParam(2)));
end

rule "Deactivate bot"

    when
        pkg : MsgPacket(command matches "deactivate")
    then
    	# aochatbot.active(pkg.getParam(1), false);
  		session.write(pkg.getReply("Deactivate bot " + pkg.getParam(2)));
end

rule "Spawn bot"

    when
        pkg : MsgPacket(command matches "spawn")
    then
	    # aochatbot.spawn(pkg.getParam(1));
  		session.write(pkg.getReply("Bot spawning"));
end

rule "Kill bot"

    when
        pkg : MsgPacket(command matches "kill")
    then
	    # aochatbot.spawn(pkg.getParam(1));
  		session.write(pkg.getReply("Bot terminating"));
end