package apbot

import ao.apbot.pkg.*;

dialect  "mvel"

global org.apache.mina.core.session.IoSession session
global ao.apbot.AoChatBot aoChatBot

rule "ChannelUpdatePacket"

    when
        pkg : ChannelUpdatePacket()
    then
  		System.out.println( "ChannelUpdatePacket" );
end

rule "FriendUpdatePacket"

    when
        pkg :FriendUpdatePacket ()
    then
  		System.out.println( "FriendUpdatePacket" );

end
