package apbot

import java.util.Calendar;
import ao.apbot.codec.*;
import ao.apbot.pkg.*;
import ao.apbot.AoChatBot;

global org.apache.mina.core.session.IoSession session;
global ao.apbot.AoChatBot aochatbot;

dialect  "mvel"

rule "ChannelUpdatePacket"

    when
        pkg : ChannelUpdatePacket()
    then
  		System.out.println( "ChannelUpdatePacket" );
end

rule "FriendUpdatePacket"

    when
        pkg :FriendUpdatePacket ()
    then
  		System.out.println( "FriendUpdatePacket" );

end
