package apbot

import ao.apbot.codec.Fact;
import ao.apbot.pkg.*;

dialect  "mvel"

//list any import classes here.

//declare any global variables here

rule "ChannelUpdatePacket"

    when
        pkg : ChannelUpdatePacket()
    then
  		System.out.println( "ChannelUpdatePacket" );
end

rule "FriendUpdatePacket"
    //include attributes such as "salience" here...
    when
        pkg :FriendUpdatePacket ()
    then
  		System.out.println( "FriendUpdatePacket" );

end
